### ISSUE TITLE
Still doesn't work for me

### ISSUE THREAD

**Issue by olesgedz** [school21moscow/42_RU_vogsphere_access#1]
jblack-b@42.FR's password:
kinit: krb5_get_init_creds: unable to reach any KDC in realm 42.FR, tried 0 KDCs

**Comment by apiyron** [comment]
@olesgedz Did you try work with Vogsphere repositories via school Wi-FI ? It's not possible to work outside school network for now. 🙂

**Comment by olesgedz** [comment]
@apiyron  I always thought, it's the idea xD
